# Generated by Django 5.2.7 on 2026-01-26 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_jobseekerprofile_skills_recruiterprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='github_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='leetcode_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='portfolio_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
